--PACHETE
--PERMIT INCAPSULAREA TIPURILOR DE VARIABILE, CONSTANTE, SUBPROGRAME, CURSORI SI EXCEPTII IN MODULE;
--ESTE COMPUSA DIN DOUA PARTI: SPECIFICATIA SI CORPUL PACHETULUI;

--SPECIFICATIA PACHETULUI
--ESTE INTERFATA PACHETULUI;
--SE DECLARA TIPURILE, VARIABILELE, CONSTANTELE, EXCEPTIILE, CURSORELE SI SUBPROGRAMELE;
--CONTINE INFORMATIA DESPRE CONTINUTUL PACHETULUI SI EXCLUDE CODUL;
--SINTAXA GENERALA PENTRU CREARE:
--CREATE OR REPLACE PACKAGE NUME_PACHET IS|AS
--DECLARATII;
--END NUME_PACHET;


--EXEMPLU DE SPECIFICATIE PACHET:
CREATE OR REPLACE PACKAGE pachet AS
    status CONSTANT VARCHAR(10) := 'Activ';
END;
/


--CORPUL PACHETULUI
--ESTE DECLARAT CODUL PENTRU DIFERITE METODE DECLARATE IN SPECIFICATIA PACHETULUI;
--SINTAXA GENERALA PENTRU CREARE:
--CREATE OR REPLACE PACKAGE BODY NUME_PACHET IS|AS
--DECLARATII;
--BEGIN
--EXCEPTION
--END NUME_PACHET;


--EXEMPLU DE CORP PACHET:
CREATE OR REPLACE PACKAGE BODY pachet IS
BEGIN
    dbms_output.put_line(status);
END pachet;
/

--PENTRU A ELIMINA UN PACHET SE FOLOSESTE URMATOAREA SINTAXA:
--DROP PACKAGE [BODY] NUME_PACHET;

--PENTRU A FOLOSI VARIABILELE SAU SUBPROGRAMELE DINTR-UN PACHET SE FOLOSESTE URMATOAREA SINTAXA:
--NUME_PACHET.NUME_ELEMENT;
