-- OPERATORUL := SAU DACA PUNEM DEFAULT ESTE ACELASI LUCRU
-- SINTAXA GENERALA: variable_name datatype [NOT NULL] [:= initial_value];
--VARIABILE LOCALE (CELE DIN BLOCUL INTERIOR) SI GLOBALE (CELE DIN PRIMUL BLOC DECLARE)


--EXEMPLU CU SINTAXA GENERALA
DECLARE
    mesaj VARCHAR2(20) NOT NULL := 'Hello';
BEGIN
    null;
END;
/


--EXEMPLU CU SELECT INTO SI %TYPE
DECLARE
    s_nume pisica.nume%TYPE;
    s_pret pisica.pret%TYPE;
BEGIN
 SELECT
    nume, pret
 INTO
    s_nume, s_pret;
 FROM
    pisica;
END;
/


--CONSTANTE = O DATA CE AM DAT VALOARE, NU SE MAI POATE SCHIMBA
-- SINTAXA: VARIABLE_NAME CONSTANT DATATYPE := VALUE


--LITERALI = VALORILE VARIABILELOR
--NUMERIC LITERAL (EX: 50);
--CHARACTER LITERAL (EX: 'A');
--STRING LITERAL (EX: 'HELLO');
--BOOLEAN LITERAL (EX: TRUE);
--DATE AND TIME LITERAL (EX: '1985-12-25');


--OPERATORI
-- PENTRU EXPONENTIAL **
-- PENTRU DIFERIT, SUNT MAI MULTE MODALITATI != <> ~=
