--EXCEPTII
--EXISTA DOUA TIPURI DE EXCEPTII:
--EXCEPTII DEFINITE DE SISTEM;
--EXCEPTII DEFINITE DE UTILIZATOR;
--SE POT PRINDE SI MANIPULA CATE EXCEPTII SE DORESTE;
--EXISTA IMPLICIT INSTRUCTIUNEA DEFAULT, IN FELUL URMATOR: WHEN OTHERS THEN;
--SINTAXA GENERALA PENTRU PRINDEREA EXCEPTIILOR:
--DECLARE [...]
--BEGIN [...]
--EXCEPTION 
--WHEN EXCEPTION 1..N THEN
--Sn;
--WHEN OTHERS THEN
--Sn;
--END;

--EXEMPLE DE EXCEPTII PREDEFINITE:
--COLLECTION_IS_NULL;
--INVALID_CURSOR;
--NO_DATA_FOUND (APARE LA SELECT INTO);
--TOO_MANY_ROWS;
--ZERO_DIVIDE;
--ETC;


--EXEMPLU PRINDERE EXCEPTIE:
DECLARE
    zero number := 0;
    zece number := 10;
    total number;
BEGIN
    total := zece/zero;
EXCEPTION
  WHEN ZERO_DIVIDE THEN
    dbms_output.put_line('Nu merge impartirea la zero.');
  WHEN OTHERS THEN
    dbms_output.put_line('Eroare.');
END;
/
--OBS: MAI SUS ESTE O EXCEPTIE DEFINITA DE SISTEM;


--SE POATE ARUNCA O EXCEPTIE IN MOD EXPLICIT FOLOSIND INSTRUCTIUNEA RAISE;
--SINTAXA GENERALA PENTRU ARUNCAREA EXCEPTIILOR:
--DECLARE 
--NUME_EXCEPTIE EXCEPTION;
--BEGIN
--IF CONDITIE THEN
--END IF;
--EXCEPTION
--WHEN NUME_EXCEPTIE THEN
--Sn;
--END;



--EXEMPLU PENTRU ARUNCAREA UNEI EXCEPTII DECLARATE:
DECLARE
    id number := 5;
    exceptie_invalid_id EXCEPTION;
BEGIN
  IF id <= 10 THEN
    RAISE exceptie_invalid_id;
  END IF;
EXCEPTION
  WHEN exceptie_invalid_id THEN
    dbms_output.put_line('Invalid id.');
END;
/
--OBS: MAI SUS ESTE O EXCEPTIE DEFINITA DE UTILIZATOR;


