--TRIGGERS
--TRIGGER-UL ESTE UN DECLANSATOR, CA UN RASPUNS LA EVENIMENTE APARUTE;
--EXEMPLU DE EVENIMENTE: 
--MANIPULAREA BAZEI DE DATE (DML: DELETE/INSERT/UPDATE);
--DEFINIREA BAZEI DE DATE (DDL: CREATE/ALTER/DROP);
--OPERAREA BAZEI DE DATE (LOGON/LOGOFF/STARTUP/SHUTDOWN);
--SINTAXA CREARII UNUI TRIGGER:
--CREATE OR REPLACE TRIGGER NUME
--BEFORE/AFTER/INSTEAD OF INSERT OR UPDATE OR DELETE ON NUME_TABEL
--FOR EACH ROW (LA NIVEL DE RAND SI NU LA NIVEL DE TABELA)
--WHEN CONDITIE (ESTE LA NIVEL DE RAND)
--DECLARE [...]
--BEGIN [...]
--EXCEPTION [...]
--END;

--OBS: INSTEAD OF SE FOLOSESTE PENTRU TABELELE VIRTUALE "VIEWS" PENTRU A PERMITE MANIPULAREA DATELOR;


--EXEMPLU TRIGGER:
CREATE OR REPLACE TRIGGER modificare_salariu 
BEFORE DELETE OR INSERT OR UPDATE ON Angajat 
FOR EACH ROW 
WHEN (NEW.id > 0) 
DECLARE 
    diferenta_salariu number; 
BEGIN 
    diferenta_salariu := :NEW.salariu - :OLD.salariu; 
    dbms_output.put_line('Diferenta salariu: ' || diferenta_salariu); 
END; 
/ 
--OBS: :NEW SI :OLD SUNT FOLOSITE CA REFERINTE PENTRU INREGISTRARILE NOI SI VECHI;
--OBS: NEW SI OLD SE POATE FOLOSI IN CLAUZA WHEN, DAR FARA ':' INAINTE;


--Eveniment declansator	  :NEW	  :OLD
--INSERT	               DA	   NU
--UPDATE	               DA	   DA
--DELETE	               NU	   DA

