--FUNCTII STRING
--EXEMPLU:
--CONCAT(X,Y); --CONCATENEAZA
--INITCAP(X); -- CONVERTESTE PRIMA LITERA DIN FIECARE CUVANT SI O TRANSFORMA IN LITERA MARE
--INSTR(X, FIND_STRING[START][OCCURENCE]); 
--EXEMPLU INSTR(X,'E'); --SPUNE POZITIA PRIMULUI E DIN X;
--LENGTH(X); --NUMARUL DE CARACTERE DINTR-UN STRING
--LOWER(X); --CONVERTESTE IN LITERE MICI UN STRING
--LTRIM(X,[TRIM_STRING]);
--EXEMPLU: LTRIM(X,'.'); --TAIE ACEL CARACTER DIN STANGA STRING-ULUI
--RTRIMP(X,[TRIM_STRING]);
--TRIM([TRIM_CHAR FROM] X);
--EXEMPLU: TRIM('.' FROM X);
--NVL(X,VALUE); -- RETURNEAZA VALOAREA DACA X E NULL, ALTFEL RETURNEAZA X
--NVL2(X,VALUE1,VALUE2); --RETURNEAZA VALUE1 DACA X NU E NULL, ALTFEL RETURNEAZA VALUE2
--REPLACE(X,SEARCH_STRING,REPLACE_STRING); --INLOCUIESTE UN SIR DE CARACTERE
--SUBSTR(X, START[,LENGTH]); --RETURNEAZA UN SUBSTRING DINTR-UN STRING
--UPPER(X); --TOATE LITERELE DINTR-UN STRING DEVIN LITERE MARI


--VECTOR
--SINTAXA 1:
--CREATE OR REPLACE TYPE NUME IS VARRAY(N) OF <TIP_DATA>
--SINTAXA 2:
--TYPE NUME IS VARRAY(N) OF <TIP_DATA>
--EXEMPLU:
--TYPE NOTE IS VARRAY(5) OF INTEGER;
-- VECTORUL INCEPE DE LA INDEXUL 1, SI ESTE UNIDIMENSIONAL
-- ACEASTA SINTAXA ESTE PENTRU CREAREA TIPULUI DE VECTOR


--EXEMPLU
DECLARE
    TYPE note_vector IS VARRAY(7) OF INTEGER;
    note note_vector;
BEGIN
    note := note_vector(3,5,7,6,8,9,10);
  FOR i in 1 .. note.count LOOP
    dbms_output.put_line(note(i));
  END LOOP;
END;
/

